config:
  name: "Switch DNS Settings Audit"
  description: "Collect DNS configurations from all network switches"
  version: "1.0"
  author: "Stephen Pollard"

api_calls:
  - name: "get_dns_settings"
    api:
      endpoint: "devices"
      method: "getDeviceManagementInterface"
      requires_device: true
      output_filter:
        - "dns1"
        - "dns2"
        - "staticDns"
        - "vlan"
        - "staticIp"
        - "staticGatewayIp"
        - "staticSubnetMask"
    output: "switch_dns" 