config:
  name: "PoE Ports Audit"
  description: "Collect PoE information from all switches"
  version: "1.0"
  author: "Stephen Pollard"

api_calls:
  - name: "get_poe_statuses"
    api:
      endpoint: "devices.switch.ports"
      method: "getDeviceSwitchPortsStatuses"
      requires_device: true
      output_filter:
        - "portId"
        - "enabled"
        - "status"
        - "isUplink"
        - "speed"
        - "duplex"
        - "errors"
        - "warnings"
        - "cdp"
        - "lldp"
        - "clientCount"
        - "powerUsageInWh"
        - "powerDrawInWh"
        - "powerMode"
        - "powerAllocatedInWh"
    output: "poe_ports" 