config:
  name: "Switch Ports Audit"
  description: "Collect all switch port configurations"
  version: "1.0"
  author: "Stephen Pollard"

api_calls:
  - name: "get_switches"
    api:
      endpoint: "networks.devices"
      method: "getNetworkDevices"
      filters:
        productTypes: ["switch"]
    output: "switches"
  
  - name: "get_ports"
    api:
      endpoint: "devices.switch.ports"
      method: "getDeviceSwitchPorts"
      requires_device: true
    output: "ports" 